version: 2
jobs:
  checkout:
    docker: 
      - image: circleci/python
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: ls -al workspace
      - run: $PWD/scripts/checkout.sh /tmp/workspace $PWD/scripts/publication.config
      - run: cat /tmp/workspace/checkouts.txt
      - run:
          name: List the files which have been created
          command: ls -al /tmp/workspace/*
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - checkouts.txt
            - links.txt
            - src
  extract-jsonld-details:
    docker:
      - image: informatievlaanderen/oslo-ea-to-rdf:json-ld-format
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Extract json details required (part1)
          command: $PWD/scripts/extract-what.sh jsonld
      - run:
          name: Show the report (for debugging purposes)
          command: cat /tmp/workspace/report/*.report
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - checkouts.txt
            - links.txt
            - reports
            - src	    
  render-details:
    docker:
      - image: informatievlaanderen/oslo-specification-generator:javascript
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install jq (should be in docker)
          command: apt-get update && apt-get install jq
      - run:
          name: Render HTML version of merged ttl file
          command: $PWD/scripts/render-details.sh /tmp/workspace json
      - run:
          name: List the files which have been created
          command: ls -al /tmp/workspace/html/*
      - run:
          name: Show the report (for debugging purposes)
          command: cat /tmp/workspace/report/*.report
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - html/
            - report/
            - ttl/
            - src/
  expand-links:
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: $PWD/scripts/expand-links.sh /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - html/
            - reports/	    
            - src/
  create-artifact:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "84:ef:18:e6:4c:b3:fa:38:4e:d2:47:09:e9:be:0f:e6"
      - run:
          name: Checkout target repo
          workdir: /tmp
          command: |
            git clone git@github.com:Informatievlaanderen/OSLO-Generated.git
            cd OSLO-Generated && git fetch origin && git checkout -B "${CIRCLE_BRANCH}" "origin/${CIRCLE_BRANCH}"
            rm -rf *
      - run:
          name: Copy static assets
          command: |
            cp -R site-skeleton/* /tmp/OSLO-Generated/
      - run:
          name: Copy generated assets
          workdir: /tmp/workspace
          command: |
            cp -R voc/* /tmp/OSLO-Generated/ns/
            cp ap/*.jsonld /tmp/OSLO-Generated/context/
            cp -R ap/* /tmp/OSLO-Generated/doc/applicatieprofiel/
      - run:
          name: Push results to github
          workdir: /tmp/OSLO-Generated
          command: |
            git config user.email "oslo@kb.vlaanderen.be"
            git config user.name "Circle CI Builder"
            git add .
            git commit -m "Applying changes from commit ${CIRCLE_SHA1}" --allow-empty
            git push origin "${CIRCLE_BRANCH}"
workflows:
  version: 2
  generate_documentation:
    jobs:
      - checkout
      - extract-jsonld-details:
          requires:
            - checkout
      - render-details:
          requires:
            - extract-jsonld-details	  
      - expand-links:
          requires:
            - render-details
      - create-artifact:
          requires:
            - expand-links
