version: 2
jobs:
  extract-vocabularia:
    docker:
      - image: informatievlaanderen/oslo-ea-to-rdf:circleci
    steps:
      - checkout
      - run:
          name: Extract ttl data for each diagram
          command: |
            jq -r '.[] | select(.type | contains("voc")) | @sh "java -jar /app/ea-2-rdf.jar convert -i src/\(.eap) -c config/config-voc.json -d \(.diagram) -o /tmp/workspace/ttl/\(.name).ttl"' < config/eap-mapping.json | bash -e
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ttl/
  extract-application-profiles:
    docker:
      - image: informatievlaanderen/oslo-ea-to-rdf:circleci
    steps:
      - checkout
      - run:
          name: Extract tsv data for each diagram
          command: |
            jq -r '.[] | select(.type | contains("ap")) | @sh "java -jar /app/ea-2-rdf.jar tsv -i src/\(.eap) -c config/config-ap.json -d \(.diagram) -o /tmp/workspace/tsv/\(.name).tsv"' < config/eap-mapping.json | bash -e
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - tsv/
  add-voc-contributors:
    docker:
      - image: informatievlaanderen/oslo-specification-generator:circleci
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Add contributors to vocabulary ttl file
          command: |
            jq -r '.[] | select(.type | contains("voc")) | @sh "python /app/specgen/generate_vocabulary.py --add_contributors --rdf /tmp/workspace/ttl/\(.name).ttl --csv src/stakeholders.csv --csv_contributor_role_column \(.contributors) --output /tmp/workspace/ttl/\(.name).ttl"' < config/eap-mapping.json | bash -e
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ttl/
  render-voc-html:
    docker:
      - image: informatievlaanderen/oslo-specification-generator:circleci
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Render HTML version of merged ttl file
          command: |
            jq -r '.[] | select(.type | contains("voc")) | @sh "python /app/specgen/generate_vocabulary.py --schema \(.template) --schema_folder templates/ --rdf /tmp/workspace/ttl/\(.name).ttl --output /tmp/workspace/voc/\(.name)/index.html"' < config/eap-mapping.json | bash -e
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - voc/
  render-voc-rdf:
    docker:
      - image: circleci/ruby
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install dependencies
          command: |
            gem install linkeddata && mkdir -p /tmp/workspace/voc
            sed -i '/TBD/d' /tmp/workspace/ttl/gebouw.ttl
            sed -i '/"TODO"^^xsd:date/d' /tmp/workspace/ttl/openbaardomein.ttl
            #sed -i '/"TODO"^^xsd:date/d' /tmp/workspace/ttl/weg.ttl
      - run:
          name: Turn TODO into proper URIs
          command: find /tmp/workspace/ttl -type f | xargs sed -i 's/TODO/http:\/\/example.com\/TODO/g'
      - run:
          name: Generate ntriples
          command: |
            for model in $(ls /tmp/workspace/ttl | sed 's/.ttl//'); do
              rdf serialize --input-format turtle --output-format ntriples /tmp/workspace/ttl/${model}.ttl -o /tmp/workspace/voc/${model}.nt
            done
      - run:
          name: Generate rdfxml
          command: |
            for model in $(ls /tmp/workspace/ttl | sed 's/.ttl//'); do
              rdf serialize --input-format turtle --output-format rdfxml /tmp/workspace/ttl/${model}.ttl -o /tmp/workspace/voc/${model}.rdf
            done
      - run:
          name: Generate jsonld
          command: |
            for model in $(ls /tmp/workspace/ttl | sed 's/.ttl//'); do
              rdf serialize --input-format turtle --output-format jsonld /tmp/workspace/ttl/${model}.ttl -o /tmp/workspace/voc/${model}.jsonld
              cp /tmp/workspace/voc/${model}.jsonld /tmp/workspace/voc/${model}.json
            done
      - run:
          name: Generate turtle
          command: |
            for model in $(ls /tmp/workspace/ttl | sed 's/.ttl//'); do
              cp /tmp/workspace/ttl/${model}.ttl /tmp/workspace/voc/${model}.ttl
            done
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - voc/
  render-ap-html:
    docker:
      - image: informatievlaanderen/oslo-specification-generator:circleci
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Render HTML of AP tsv file
          command: |
            jq -r '.[] | select(.type | contains("ap")) | @sh "python /app/specgen/generate_vocabulary.py --ap --csv /tmp/workspace/tsv/\(.name).tsv --csv_contributor src/stakeholders.csv --csv_contributor_role_column \(.contributors) --title \(.title) --name \(.name) --schema \(.template) --schema_folder templates/ --output /tmp/workspace/ap/\(.name)/index.html"' < config/eap-mapping.json | bash -e
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ap/
  render-ap-jsonld:
    docker:
      - image: informatievlaanderen/oslo-specification-generator:circleci
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Render jsonld version of AP tsv file
          command: |
            for model in $(ls /tmp/workspace/tsv | sed 's/.tsv//'); do
              python /app/specgen/generate_jsonld.py --input /tmp/workspace/tsv/${model}.tsv --output /tmp/workspace/ap/${model}.jsonld
            done
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ap/
  create-artifact:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "84:ef:18:e6:4c:b3:fa:38:4e:d2:47:09:e9:be:0f:e6"
      - run:
          name: Checkout target repo
          workdir: /tmp
          command: |
            git clone git@github.com:Informatievlaanderen/OSLO-Generated.git
            cd OSLO-Generated && git checkout -B "${CIRCLE_BRANCH}"
            rm -rf *
      - run:
          name: Copy static assets
          command: |
            cp -R site-skeleton/* /tmp/OSLO-Generated/
      - run:
          name: Copy generated assets
          workdir: /tmp/workspace
          command: |
            cp -R voc/* /tmp/OSLO-Generated/ns/
            cp ap/*.jsonld /tmp/OSLO-Generated/context/
            cp -R ap/* /tmp/OSLO-Generated/doc/applicatieprofiel/
      - run:
          name: Push results to github
          workdir: /tmp/OSLO-Generated
          command: |
            git config user.email "oslo@kb.vlaanderen.be"
            git config user.name "Circle CI Builder"
            git add .
            git commit -m "Applying changes from commit ${CIRCLE_SHA1}" --allow-empty
            git push origin "${CIRCLE_BRANCH}"
workflows:
  version: 2
  generate_documentation:
    jobs:
      - extract-vocabularia
      - extract-application-profiles
      - add-voc-contributors:
          requires:
            - extract-vocabularia
      - render-voc-html:
          requires:
            - add-voc-contributors
      - render-voc-rdf:
          requires:
            - add-voc-contributors
      - render-ap-html:
          requires:
            - extract-application-profiles
      - render-ap-jsonld:
          requires:
            - extract-application-profiles
      - create-artifact:
          requires:
            - render-voc-html
            - render-voc-rdf
            - render-ap-html
            - render-ap-jsonld
